name: "Continuous Integration"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run:
    name: "tests & coverage"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install hatch
      run: |
        python -m pip install hatch

    - name: Tests
      env:
        MG_HOST: ${{ secrets.MG_HOST }}
        MG_PORT: ${{ secrets.MG_PORT }}
        MG_PORT_ALT: ${{ secrets.MG_PORT_ALT }}
      run: hatch run cov
